{% set version = "5.15.2" %}

package:
  name: qt-main
  version: {{ version }}

source:
  - url: https://download.qt.io/archive/qt/{{ version.rpartition('.')[0] }}/{{ version }}/single/qt-everywhere-src-{{ version }}.tar.xz
    sha256: 3a530d1b243b5dec00bc54937455471aaa3e56849d2593edb8ded07228202240
    folder: qt
    patches:
      # qtbase
      - patches/qt/0002-qtbase-osx-allow-any-xcrun-in-PATH.patch    # [not win]
      - patches/qt/0003-qtbase-use-better-clang-optimize-size.patch  # [not win]
      - patches/qt/0004-qtbase-never-enable-new-dtags.patch  # [not win]
      - patches/qt/0005-qtbase-link-xcb-shm.patch
      - patches/qt/0009-qtbase-fix-hardcoded-sysroot-path.patch  # [not win]

      # The following patches are required to compile Qt using native arm64
      # compilers
      - patches/qt/0008-Force-host-to-be-the-same-as-the-target.patch        # [osx]
      - patches/qt/0009-Ensure-no-cross-compilation-checks-are-done.patch    # [osx]
      - patches/qt/0010-Try-to-set-arm64-explicitly.patch                    # [arm64]
      - patches/qt/0011-Prevent-stat64-definition.patch                      # [arm64]
      - patches/qt/qt.patch  # [unix]
      - patches/qt/0011-qtbase-Fix-QMAKE_LIBDIR_X11-and-QMAKE_LIBDIR_OPENGL-.patch # [linux]
      #- patches/qt/linux_x86_64.patch   # [linux and x86_64]
      #- patches/qt/linux_aarch64.patch  # [linux and aarch64]

      # Patch for c++11 compatibility
      - patches/qt/0012-include-utility-in-mbgl-util-unique_any.patch

      # Patch for openssl 3 compatibility, picked up from kde's patchset
      - patches/qt/0013-upstream-fixes-to-support-OpenSSL-3.0.patch

      # This helps compatibility between qt and CXX17
      # https://github.com/conda-forge/qt-main-feedstock/pull/136
      # https://github.com/conda-forge/libcxx-feedstock/issues/114#issuecomment-1490672500
      - patches/qt/0014-remove-usage-of-unary-operator.patch

      # https://github.com/xkbcommon/libxkbcommon/blob/6073565903488cb5b9a8d37fdc4a7c2f9d7ad04d/NEWS#L11
      # https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/70
      - patches/qt/0015-remove-deleted-xkb-keys.patch

      # https://github.com/Homebrew/homebrew-core/pull/145729
      - patches/qt/0016-qmake-xcode15.patch

      # https://bugreports.qt.io/browse/QTBUG-121183
      # https://codereview.qt-project.org/c/qt/qtbase/+/532555
      - patches/qt/0017-Backport-fixes-for-compatibility-with-mysql-8.3.patch
      - patches/qt/0018-Avoid-usage-of-mysql_ssl_set.patch

      # https://github.com/conda-forge/qt-main-feedstock/pull/282#issuecomment-2349349013
      # icu 75 requires C++17, so enable it also in the dummy compilation of a icu snippet that qmake does for configuration
      #- patches/qt/0019-use-cxx17-for-icu-config-tests.patch
      # similarly, mapbox-gl-native uses icu, so we need to make sure that it compiles with C++17
      #- patches/qt/0020-compile-mapbox-gl-native-with-cxx17-for-icu75-compat.patch
      # commented as Anaconda is using icu 73.1

      # mapbox-gl-native uses a old vendored boost, make sure that we used an up-to-date boost instead
      - patches/qt/0021-unvendor-boost-from-mapbox-gl-native.patch
      # Taken from debian for gcc 13 compatibility
      # https://github.com/conda-forge/qt-main-feedstock/pull/289#issuecomment-2354739087
      - patches/qt/0022-gcc_13.patch
      # Patch from OpenMandriva also used by archlinux
      - patches/qt/0023-work-around-pyside2-llvm16.patch
      # Fix compilation with clang 18, see https://bugs.gentoo.org/936486
      - patches/qt/0024-fix-mapbox-gl-native-with-clang-18.patch
      # Fix compilation on osx, see https://codereview.qt-project.org/c/qt/qtbase/+/378706
      - patches/qt/0025-add-missing-macos-headers.patch
      # Fix compilation on unix, see https://github.com/Tencent/rapidjson/issues/718
      - patches/qt/0026-remove-rapidjson-non-compiling-assignment-operator.patch

  - url: https://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-64-mesa_12_0_rc2.7z     # [win64]
    sha256: 2a0d2f92c60e0962ef5f6039d3793424c6f39e49ba27ac04a5b21ca4ae012e15                                      # [win64]
    folder: opengl32sw                                                                                            # [win64]

  - url: https://download.qt.io/development_releases/gnuwin32/gnuwin32.zip  # [win]
    folder: gnuwin32  # [win]
    sha256: 4a9dc893cc0a1695a16102a42ef47ef2e228652891f4afea67fadd452b63656b  # [win]

build:
  number: 13
  version: {{ version }}
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt-main', max_pin='x.x') }}
  missing_dso_whitelist:  # [osx]
    - /usr/lib/libbsm.0.dylib  # [osx]
    - /usr/lib/libcups.2.dylib  # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib/libsandbox.1.dylib  # [osx]
    - '/System/Library/Frameworks/CoreLocation.framework/**'  # [osx]
    #- '*/api-ms-win-core-winrt-l1-1-0.dll'  # [win]
    #- '*/api-ms-win-core-winrt-string-l1-1-0.dll'  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    # For fontconfig + freetype
    - pkg-config                         # [unix]
    - make                               # [unix]
    - ninja
    - bison                              # [linux]
    - flex                               # [linux]
    - gperf                              # [linux]
    - msys2-gperf                        # [win]
    - msys2-bison                        # [win]
    - msys2-flex                         # [win]
    - jom                                # [win]
    - curl                               # [win]
    - perl 5.*
    # Add readline here, so that newest readline is used.
    # Otherwise build and host might end up with two different versions
    # If they do, merge_build_host will fail.
    - readline                           # [linux]
    - binutils                           # [linux]

  host:
    # For pkg-config gl, fontconfig + freetype
    - pthread-stubs 0.3                  # [linux]
    - dbus {{ dbus }}                    # [linux]
    - fontconfig {{ fontconfig }}        # [linux]
    - freetype {{ freetype }}            # [linux]
    - glib {{ glib }}                    # [not win]
    - gst-plugins-base {{ gst_plugins_base }} # [not win]
    - gstreamer {{ gstreamer }}          # [not win]
    - libxkbcommon {{ libxkbcommon }}    # [linux]
    - icu {{ icu }}
    # jpeg-turbo currently has some conflicting issues in conda-forge
    # see: https://github.com/conda-forge/conda-forge.github.io/issues/673
    - jpeg {{ jpeg }}
    - libpng {{ libpng }}
    - sqlite {{ sqlite }}
    - mysql-devel {{ mysql_libs }}  # [unix]
    - libpq {{ libpq }}
    - zlib {{ zlib }}
    - libxcb {{ libxcb }}               # [linux]
    - openssl {{ openssl }}
    - libkrb5 {{ libkrb5 }}
    - harfbuzz {{ harfbuzz }}           # [linux]
    # OpenGL support
    - libdrm {{ libdrm }}                            # [linux]
    - libgl-devel  {{ libgl }}                       # [linux]
    - libegl-devel {{ libglvnd }}                    # [linux]
    # For QDoc
    # http://doc.qt.io/Qt-5/qdoc-guide-clang.html
    # Only libclang is needed, but needs the full package for detection.
    - llvm 20.1.8  
    - clangdev 20.1.8
    # Ensure that build and host have the same clang version on osx
    # otherwise qt6 may be out of sync compared to the pinned compiler
    # version
    - libclang {{ cxx_compiler_version }}         # [osx]
    - libclang 20.1.8                             # [not osx]
    - libcups {{ libcups }}                       # [linux]
    - zstd {{ zstd }}
    # The xcb-util packages are necessary to build the Qt xcb plugin.
    # It was decided to not use CDTs for qt to resolve issues
    # that may exhibit as segfault due to missing libraries
    # in some lighter weight linux installations
    # https://github.com/conda-forge/qt-main-feedstock/issues/32
    - xcb-util {{ xcb_util }}                          # [linux]
    - xcb-util-wm {{ xcb_util_wm }}                    # [linux]
    - xcb-util-keysyms {{ xcb_util_keysyms }}          # [linux]
    - xcb-util-image {{ xcb_util_image }}              # [linux]
    - xcb-util-renderutil {{ xcb_util_renderutil }}    # [linux]
    - xorg-libx11 {{ xorg_libx11 }}                    # [linux]
    - xorg-libxext {{ xorg_libxext }}                  # [linux]
    - xorg-libxdamage {{ xorg_libxdamage }}            # [linux]
    - xorg-libsm {{ xorg_libsm }}                      # [linux]
    - xorg-libice {{ xorg_libice }}                    # [linux]
    # https://github.com/conda-forge/staged-recipes/pull/22084
    - xorg-libxxf86vm {{ xorg_libxxf86vm }}            # [linux]
    - xorg-xorgproto {{ xorg_xorgproto }}              # [linux]
    # qtlocation requires mapbox-gl-native that uses libbost-headers
    - libboost-headers {{ libboost_devel }}
  run:
    # bounds throuhg run_exports
  run_constrained:
    - qt >=5.15.2,<6
test:
  requires:
    - {{ compiler('cxx') }}
    - make                               # [unix]
  files:
    - test/qt/hello.pro
    - test/qt/main-qtwebengine.cpp
    - test/qt/main.cpp
    - test/qt/main.qml
    - test/qt/qml.qrc
    - test/qt/qrc_qml.cpp
    - test/qt/qtwebengine.pro
    - xcodebuild
    - xcrun
  script: run_qt_test.sh                 # [not win]
  script: run_qt_test.bat                # [win]
  commands:
    # sql plugin
    - test -f $PREFIX/plugins/sqldrivers/libqsqlite${SHLIB_EXT}            # [unix]
    - if not exist %LIBRARY_PREFIX%\plugins\sqldrivers\qsqlite.dll exit 1  # [win]

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  license_family: LGPL
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  skip-lints:
    - has_run_test_and_commands
    - should_use_compilers
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - duncanmmacleod
    - gillins
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
    - Tobias-Fischer
