{% set version = "6.7.2" %}
{% set next_major_version = version.split(".")[0] | int + 1 %}

package:
  name: qt-main
  version: {{ version }}

build:
  number: 0
  skip: True  # [s390x]
  run_exports:
    - {{ pin_subpackage('qt-main', max_pin='x.x') }}

requirements:
  run:
    - qtbase >={{ version }},<{{ next_major_version }}
    - qtsvg >={{ version }},<{{ next_major_version }}
    - qtshadertools >={{ version }},<{{ next_major_version }}
    - qtdeclarative >={{ version }},<{{ next_major_version }}
    - qtimageformats >={{ version }},<{{ next_major_version }}
    - qttools >={{ version }},<{{ next_major_version }}
    - qttranslations >={{ version }},<{{ next_major_version }}
    - qt5compat >={{ version }},<{{ next_major_version }}
    - qtwebsockets >={{ version }},<{{ next_major_version }}
    - qtwebchannel >={{ version }},<{{ next_major_version }}

about:
  home: https://www.qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  license_family: LGPL
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  skip-lints:
    - missing_tests
  recipe-maintainers:
    - bwingconda
