{% set name = "qt-main" %}
{% set version = "6.10.2" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  # https://doc.qt.io/qt-6/qt-releases.html#binary-compatibility
  run_exports:
    - {{ pin_subpackage('qt-main', max_pin='x.x') }}

requirements:
  host:
    - qtbase {{ version }}
    - qtsvg {{ version }}
    - qtshadertools {{ version }}
    - qtdeclarative {{ version }}
    - qtimageformats {{ version }}
    - qttools {{ version }}
    - qttranslations {{ version }}
    - qt5compat {{ version }}
    - qtwebsockets {{ version }}
    - qtwebchannel {{ version }}
    - qtwayland {{ version }}  # [linux]
  run:
    # Exact version handled through qtbase.
    - qtbase-devel

{% set qt_libs = [
  # Qt5Compat
  "Core5Compat",

  # QtBase
  "Concurrent",
  "Core",
  "DBus",
  "Gui",
  "Network",
  "OpenGL",
  "OpenGLWidgets",
  "Platform",
  "PrintSupport",
  "Sql",
  "Test",
  "Widgets",
  "Xml",
  "WaylandClient",              # [linux]

  # QtDeclarative
  "LabsPlatform",
  "Qml",
  "QmlCompiler",
  "QmlCore",
  "QmlModels",
  "Quick",
  "QuickControls2",
  "QuickDialogs2",
  "QuickTest",
  "QuickWidgets",

  # QtShaderTools
  "ShaderTools",

  # QtSvg
  "Svg",
  "SvgWidgets",

  # QtTools
  "Designer",
  "Help",
  "Linguist",
  "UiPlugin",
  "UiTools",

  # QtWayland
  "WaylandCompositor",          # [linux]
  "WaylandCompositorWLShell",   # [linux]
  "WaylandCompositorXdgShell",  # [linux]

  # QtWebChannel
  "WebChannel",
  "WebChannelQuick",

  # QtWebSockets
  "WebSockets",
] %}

test:
  requires:
    - pkg-config
  commands:
{% for lib_name in qt_libs %}
    - pkg-config --exists --print-errors "Qt6{{ lib_name }} >= {{ version }} Qt6{{ lib_name }} < 7"  # [unix]
{% endfor %}

about:
  home: https://www.qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  license_family: LGPL
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  skip-lints:
    - missing_tests
  recipe-maintainers:
    - bwingconda
