{% set name = "qt-main" %}
{% set version = "6.10.2" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1
  # https://doc.qt.io/qt-6/qt-releases.html#binary-compatibility
  run_exports:
    - {{ pin_subpackage('qt-main', max_pin='x.x') }}

requirements:
  host:
    - qtbase {{ version }}
    - qtsvg {{ version }}
    - qtshadertools {{ version }}
    - qtdeclarative {{ version }}
    - qtimageformats {{ version }}
    - qttools {{ version }}
    - qttranslations {{ version }}
    - qt5compat {{ version }}
    - qtwebsockets {{ version }}
    - qtwebchannel {{ version }}
    - qtwayland {{ version }}  # [linux]
  run:
    # Exact version handled through qtbase.
    - qtbase-devel

test:
  requires:
    - pkg-config
  commands:
    # Qt5Compat
    - pkg-config --exists --print-errors "Qt6Core5Compat >= {{ version }} Qt6Core5Compat < 7"  # [unix]
    # QtBase
    - pkg-config --exists --print-errors "Qt6Concurrent >= {{ version }} Qt6Concurrent < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Core >= {{ version }} Qt6Core < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6DBus >= {{ version }} Qt6DBus < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Gui >= {{ version }} Qt6Gui < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Network >= {{ version }} Qt6Network < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6OpenGL >= {{ version }} Qt6OpenGL < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6OpenGLWidgets >= {{ version }} Qt6OpenGLWidgets < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Platform >= {{ version }} Qt6Platform < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6PrintSupport >= {{ version }} Qt6PrintSupport < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Sql >= {{ version }} Qt6Sql < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Test >= {{ version }} Qt6Test < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Widgets >= {{ version }} Qt6Widgets < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Xml >= {{ version }} Qt6Xml < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6WaylandClient >= {{ version }} Qt6WaylandClient < 7"  # [linux]
    # QtDeclarative
    - pkg-config --exists --print-errors "Qt6LabsPlatform >= {{ version }} Qt6LabsPlatform < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Qml >= {{ version }} Qt6Qml < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6QmlCompiler >= {{ version }} Qt6QmlCompiler < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6QmlCore >= {{ version }} Qt6QmlCore < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6QmlModels >= {{ version }} Qt6QmlModels < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Quick >= {{ version }} Qt6Quick < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6QuickControls2 >= {{ version }} Qt6QuickControls2 < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6QuickDialogs2 >= {{ version }} Qt6QuickDialogs2 < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6QuickTest >= {{ version }} Qt6QuickTest < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6QuickWidgets >= {{ version }} Qt6QuickWidgets < 7"  # [unix]
    # QtShaderTools
    - pkg-config --exists --print-errors "Qt6ShaderTools >= {{ version }} Qt6ShaderTools < 7"  # [unix]
    # QtSvg
    - pkg-config --exists --print-errors "Qt6Svg >= {{ version }} Qt6Svg < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6SvgWidgets >= {{ version }} Qt6SvgWidgets < 7"  # [unix]
    # QtTools
    - pkg-config --exists --print-errors "Qt6Designer >= {{ version }} Qt6Designer < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Help >= {{ version }} Qt6Help < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6Linguist >= {{ version }} Qt6Linguist < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6UiPlugin >= {{ version }} Qt6UiPlugin < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6UiTools >= {{ version }} Qt6UiTools < 7"  # [unix]
    # QtWayland
    - pkg-config --exists --print-errors "Qt6WaylandCompositor >= {{ version }} Qt6WaylandCompositor < 7"  # [linux]
    - pkg-config --exists --print-errors "Qt6WaylandCompositorWLShell >= {{ version }} Qt6WaylandCompositorWLShell < 7"  # [linux]
    - pkg-config --exists --print-errors "Qt6WaylandCompositorXdgShell >= {{ version }} Qt6WaylandCompositorXdgShell < 7"  # [linux]
    # QtWebChannel
    - pkg-config --exists --print-errors "Qt6WebChannel >= {{ version }} Qt6WebChannel < 7"  # [unix]
    - pkg-config --exists --print-errors "Qt6WebChannelQuick >= {{ version }} Qt6WebChannelQuick < 7"  # [unix]
    # QtWebSockets
    - pkg-config --exists --print-errors "Qt6WebSockets >= {{ version }} Qt6WebSockets < 7"  # [unix]


about:
  home: https://www.qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  license_family: LGPL
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  skip-lints:
    - missing_tests
  recipe-maintainers:
    - bwingconda
